"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['source/main.py']
DATA_FILES = []

OPTIONS = {'argv_emulation': False,
    'iconfile':'resources/app_icon.icns',
    'plist': {'CFBundleName': 'LadderiLogical',
    'NSHumanReadableCopyrigh':'Copyright © 2015 Michal Adamkiewicz',
    "CFBundleTypeExtensions":["lil"]}
}
setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
