;----------------------------------------------------------;
; Program title: 3_Logic_examples                          ;
;----------------------------------------------------------;
; Code generated by: LadderiLogical 1.0 Alpha              ;
;----------------------------------------------------------;
; Date Compiled:  Sun Mar 12 20:54:22 2017                 ;
;----------------------------------------------------------;
; Version:  1.0                                            ;
;----------------------------------------------------------;
; Device:  PIC16F627A                                      ;
;----------------------------------------------------------;
; Oscillator: Internal 4  MHz                              ;
;----------------------------------------------------------;
; Cycles per main loop: 130                                ;
;----------------------------------------------------------;

;Registers:
;bitflag_reg_1
;tile_1_5_pulsar_counter_0
;bitflag_reg_2
;bitflag_reg_3
;special_temp_portb

;Bitflags:
;PORTA,0: flag_data
;PORTA,1: flag_store
;PORTA,2: flag_A
;PORTA,3: flag_B
;PORTA,4: flag_C
;PORTA,5: flag_6io
;PORTA,6: flag_7io
;PORTA,7: flag_8io
;special_temp_portb,0: flag_latch
;special_temp_portb,1: flag_clock
;special_temp_portb,2: flag_AB+C
;special_temp_portb,3: flag_1
;special_temp_portb,4:
;special_temp_portb,5:
;special_temp_portb,6:
;special_temp_portb,7:
;bitflag_reg_2,5: flag_reset
;bitflag_reg_2,3: flag_trigger
;bitflag_reg_1,0: tile_1_0_con
;bitflag_reg_1,1: tile_1_5_con
;bitflag_reg_1,2: tile_1_5_state
;bitflag_reg_1,3: tile_1_7_con
;bitflag_reg_1,4: tile_2_8_con
;bitflag_reg_1,5: tile_3_0_con
;bitflag_reg_1,6: tile_3_1_con
;bitflag_reg_1,7: tile_3_2_con
;bitflag_reg_2,0: tile_3_3_con
;bitflag_reg_2,1: tile_3_7_con
;bitflag_reg_2,2: tile_4_0_con
;bitflag_reg_2,4: tile_4_1_con
;bitflag_reg_2,6: tile_4_5_con
;bitflag_reg_2,7: tile_5_2_con
;bitflag_reg_3,0: tile_6_2_con
;bitflag_reg_3,1: tile_6_7_con


 LIST  P=PIC16F627A ;select device
    ;Tells MPLAB what processor IC is being used
  INCLUDE  c:\program files (x86)\microchip\MPASM Suite\P16F627A.inc
    ;include header file
    ;from default location
    ;tells the MPLAB where to find the files

  __config 0x3F10     ;sets config to; internal  I/O, no watchdog,Power
    ;up timer on, master Reset off,
    ;no brown-out, no LV program, no read protect,
    ;no code protect
;----------------------------------------------------------;
; DEFINE REGISTERS                                         ;
;----------------------------------------------------------;

 cblock  0x20
bitflag_reg_1
tile_1_5_pulsar_counter_0
bitflag_reg_2
bitflag_reg_3
special_temp_portb

 endc

init    
 MOVLW d'07'
 MOVWF CMCON         ;Disable comparators
 BSF STATUS, RP0     ;select bank1 for setup
 BSF PCON, OSCF      ;select 4 MHz
 MOVLW b'01110000'
 MOVWF TRISA         ;set PortA as inputs on designated pins
 MOVLW b'00000000'
 MOVWF TRISB         ;set PortB all outputs
 BCF STATUS, RP0     ;return to bank0 for program operation
 CLRF bitflag_reg_1
 CLRF tile_1_5_pulsar_counter_0
 CLRF bitflag_reg_2
 CLRF bitflag_reg_3
 CLRF special_temp_portb

main
 BSF bitflag_reg_1,0
 BSF bitflag_reg_1,7
 BSF bitflag_reg_2,0
 BSF bitflag_reg_1,1
 BSF bitflag_reg_1,3
 BSF bitflag_reg_1,4
 BTFSC bitflag_reg_1,0
 BTFSS PORTA,1
 goto tile_1_0_skip
 BSF bitflag_reg_1,5
 BSF bitflag_reg_1,6
 goto tile_1_0_end
tile_1_0_skip
 NOP
 NOP
 NOP
tile_1_0_end
 BCF bitflag_reg_1,0
 BTFSS bitflag_reg_1,1
 goto tile_1_5_off
 INCF tile_1_5_pulsar_counter_0,F
 MOVLW d'153'
 XORWF tile_1_5_pulsar_counter_0,W
 BTFSS STATUS,Z
 goto tile_1_5_out_0
 MOVLW d'4'
 XORWF bitflag_reg_1,F
tile_1_5_off
 CLRF tile_1_5_pulsar_counter_0
 goto tile_1_5_mid
tile_1_5_out_0
 CALL small_delay_4
tile_1_5_mid
 MOVLW d'1'
 BTFSS bitflag_reg_1,1
 CALL delay3_2;ensure it is single line (goto forced)
 BTFSS bitflag_reg_1,1
 BSF bitflag_reg_1,2
 BTFSC bitflag_reg_1,1
 BTFSS bitflag_reg_1,2
 goto tile_1_5_skip_out
 BSF bitflag_reg_2,6
 goto tile_1_5_end
tile_1_5_skip_out
 NOP
 NOP
tile_1_5_end
 BCF bitflag_reg_1,1
 BTFSC bitflag_reg_1,3
 BTFSS PORTA,2
 goto tile_1_7_skip
 BSF bitflag_reg_2,1
 goto tile_1_7_end
tile_1_7_skip
 NOP
 NOP
tile_1_7_end
 BCF bitflag_reg_1,3
 BTFSC bitflag_reg_1,4
 BTFSS PORTA,4
 goto tile_2_8_skip
 BSF bitflag_reg_3,1
 goto tile_2_8_end
tile_2_8_skip
 NOP
 NOP
tile_2_8_end
 BCF bitflag_reg_1,4
 BTFSC bitflag_reg_1,5
 BTFSS PORTA,0
 goto tile_3_0_skip
 BSF bitflag_reg_2,2
 goto tile_3_0_end
tile_3_0_skip
 NOP
 NOP
tile_3_0_end
 BCF bitflag_reg_1,5
 BTFSC bitflag_reg_1,6
 BTFSC PORTA,0
 goto tile_3_1_skip
 BSF bitflag_reg_2,4
 goto tile_3_1_end
tile_3_1_skip
 NOP
 NOP
tile_3_1_end
 BCF bitflag_reg_1,6
 BTFSC bitflag_reg_1,7
 BTFSS bitflag_reg_2,3
 goto tile_3_2_skip
 BSF bitflag_reg_2,7
 goto tile_3_2_end
tile_3_2_skip
 NOP
 NOP
tile_3_2_end
 BCF bitflag_reg_1,7
 BTFSC bitflag_reg_2,0
 BTFSS special_temp_portb,0
 goto tile_3_3_skip
 BSF bitflag_reg_2,7
 goto tile_3_3_end
tile_3_3_skip
 NOP
 NOP
tile_3_3_end
 BCF bitflag_reg_2,0
 BTFSC bitflag_reg_2,1
 BTFSS PORTA,3
 goto tile_3_7_skip
 BSF bitflag_reg_3,1
 goto tile_3_7_end
tile_3_7_skip
 NOP
 NOP
tile_3_7_end
 BCF bitflag_reg_2,1
 BCF bitflag_reg_2,3
 BTFSC bitflag_reg_2,2
 BSF bitflag_reg_2,3
 BCF bitflag_reg_2,2
 BCF bitflag_reg_2,5
 BTFSC bitflag_reg_2,4
 BSF bitflag_reg_2,5
 BCF bitflag_reg_2,4
 BCF special_temp_portb,1
 BTFSC bitflag_reg_2,6
 BSF special_temp_portb,1
 BCF bitflag_reg_2,6
 BTFSC bitflag_reg_2,7
 BTFSC bitflag_reg_2,5
 goto tile_5_2_skip
 BSF bitflag_reg_3,0
 goto tile_5_2_end
tile_5_2_skip
 NOP
 NOP
tile_5_2_end
 BCF bitflag_reg_2,7
 BCF special_temp_portb,0
 BTFSC bitflag_reg_3,0
 BSF special_temp_portb,0
 BCF bitflag_reg_3,0
 BCF special_temp_portb,2
 BTFSC bitflag_reg_3,1
 BSF special_temp_portb,2
 BCF bitflag_reg_3,1

 BCF special_temp_portb,4
 BTFSC special_temp_portb,3
 BSF special_temp_portb,4
 BCF special_temp_portb,5
 BTFSC special_temp_portb,3
 BSF special_temp_portb,5
 BCF special_temp_portb,6
 BTFSC special_temp_portb,3
 BSF special_temp_portb,6
 BCF special_temp_portb,7
 BTFSC special_temp_portb,3
 BSF special_temp_portb,7
 MOVF special_temp_portb,W
 MOVWF PORTB
 goto main
small_delay_6 nop
small_delay_5 nop
small_delay_4 return
delay3_3 Nop
delay3_2 Nop
delay3_1 Decfsz W,W
 goto delay3_1
 return
 END